/*
Generated by Generator-Camping FileVersion: 0.0.1
GeneratorName backEndCrud Template: apiController.cs FileVersion: 0.0.1
 */
using Camping.Api.Code.Controllers;
using Camping.Business.Code;
using Camping.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using Caming.Model;

namespace Camping.Api.Controllers
{
    public class <%= Name %>Controller : SimpleMapperCrudController<<%= Name %>, <%= Name %>Model>
    {
        private readonly SimpleMapperRepository<<%= Name %>, <%= Name %>Model> _repo;

        public <%= Name %>Controller(SimpleMapperRepository<<%= Name %>, <%= Name %>Model> repo)
        {
            _repo = repo;
        }
        

        protected override SimpleMapperRepository<<%= Name %>, <%= Name %>Model> Repo
        {
            get
            {
                return _repo;
            }
        }
    }
}